# Generated by Django 3.2.4 on 2021-06-13 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('photo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cacti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pot_type', models.CharField(max_length=50)),
                ('color_type', models.CharField(max_length=50)),
                ('dob', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 16, 29, 35, 419731))),
                ('species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cactus.species')),
            ],
        ),
    ]
