# Generated by Django 3.2.4 on 2021-06-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0002_alter_cacti_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cacti',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
