# Generated by Django 3.2.4 on 2021-06-14 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0006_alter_cacti_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacti',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 14, 15, 7, 39, 422481)),
        ),
    ]
