# Generated by Django 3.2.4 on 2021-06-15 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0009_alter_cacti_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacti',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 15, 14, 59, 51, 482225)),
        ),
    ]
