# Generated by Django 3.2.4 on 2021-06-16 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0010_alter_cacti_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacti',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 10, 17, 50, 859537)),
        ),
    ]
