# Generated by Django 3.0.8 on 2021-06-16 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0013_auto_20210616_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacti',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 14, 32, 27, 821975)),
        ),
    ]
