# Generated by Django 3.2.4 on 2021-06-26 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0015_auto_20210625_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cacti',
            name='color_type',
        ),
        migrations.AlterField(
            model_name='cacti',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 23, 33, 27, 849905)),
        ),
        migrations.AddField(
            model_name='cacti',
            name='color_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cactus.colortype'),
        ),
    ]
