# Generated by Django 3.2.4 on 2021-06-26 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus', '0016_auto_20210626_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colortype',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='cacti',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 23, 36, 39, 848145)),
        ),
        migrations.AlterModelTable(
            name='colortype',
            table='color_type',
        ),
    ]
